### ISSUE TITLE
Why is your wishlist on amazon.com instead of .co.uk?

### ISSUE THREAD

**Issue by mathiasverraes** [ToJans/AMA#1]
cuz it will take 18-32 days to deliver.

**Comment by ToJans** [comment]
Good question... I'll fix it. I didn't consider it...

**Comment by mathiasverraes** [comment]
Anyway make sure you are home in 18-32 days.

**Comment by ToJans** [comment]
Well, the first question was an easy one :+1:

**Comment by ToJans** [comment]
Ha, just realized your second answer implied something #HappyCamper
