### ISSUE TITLE
How many Startups ?

### ISSUE THREAD

**Issue by ylorph** [ToJans/AMA#6]

**Comment by ToJans** [comment]
Let's count:
1. CUDI - wrapper around Access/SQL DB - designed data driven apps in a few hours - had only 2 customers
2. CUDI v2 - focussed on behavior, never finished as I ran out of money.
   Fast forward to a few years later:
3. Blommekes.be - online flower shop for blokes
4. Dampen.be - online shop for vaping
5. Project "[big](https://github.com/ToJans/Big)" - event driven components in the browser; nobody got it, so I didn't continue
6. A CRM system for SME's - partnership ended.
7. A cash register product with occasionally connected clients - partnership ended
8. Joined "Paycento" : micropayments using social identity
9. [My current start-up](http://pauwels.azurewebsites.net/veranda) (and I might finally be on to something)

**Comment by ToJans** [comment]
Ha, I forgot one... I also wrote an app for a private clinic with cosmetic surgeons... So that's 10!!

**Comment by ylorph** [comment]
10 % success rate is pretty good I think , closing the issue.
