### ISSUE TITLE
Why Leaving X (for Y) ?

### ISSUE THREAD

**Issue by ylorph** [ToJans/AMA#7]
Why do you think people have the urge to say I'm leaving technology x for technology y; 
for those technical reason 

When instead I believe it's about leaving one domain for another

**Comment by ToJans** [comment]
People tend to create such posts for one of the following reasons: 
- they see `Y` as the shiny new thing, and somehow assume that everything they did in `X` should have been done using `Y`. This is my personal red flag for [`advanced beginner`](http://en.wikipedia.org/wiki/Dreyfus_model_of_skill_acquisition) level, i.e. you don't know `Y` well enough to have proper judgement. It's like being in a relationship: in the beginning it's all unicorns and rainbows, but after a while some of the incompatibilities between the 2 of you emerge... You might just dump your partner every time you get in this phase, or you might go the extra mile and try to make it work. Realizing that no relationship is perfect is a good start IMO. Same about tech `X` or `Y`. The minute you realize which tech is good for which problem, and which one isn't, you've grown past the `advanced beginner` level
- they feel like they've outgrown everyone else
- they feel they need to defend their choice.

I've done a gazillion of languages & platforms, and every single one of them had a reason why they were designed the way they were... Learn, unlearn and evolve is my motto.

PS: If anyone wants to learn functional programming combined with dependent typing/Idris, you can join me on [my learning project](https://github.com/ToJans/idris101) by submitting a pull request to it.

**Comment by ylorph** [comment]
> Learn, unlearn and evolve 

This concept is know in martial arts as Shu Ha Ri.
The First part of [this](http://www.aikidofaq.com/essays/tin/shuhari.html) article explains them pretty well I think
- Shu : "protect", "obey" , "keep" the tradition
- Ha: "disgress" from tradition
- Ri ; "Leave, transcend" the tradition , make it your own

**Comment by ylorph** [comment]
Even [Martin Fowler](http://martinfowler.com/bliki/ShuHaRi.html) is talking about Shuhari in Aïkido!

**Comment by ToJans** [comment]
I like this a lot!

**Comment by ToJans** [comment]
I'll assume we can close this one; Thanks!

**Comment by ylorph** [comment]
yes !
