### ISSUE TITLE
Quick-tool-A-minimalistic-Telnet-library

### ISSUE THREAD

**Issue by cjmeaney** [ToJans/AMA#8]
I am a really new (still in college) programmer and I could really use some help on that Telnet library. I commented on it yesterday but as it was written a few years ago I don't figure I'll get a response anytime soon. How exactly do you download/start using that class? That's exactly what I need I just have no idea how to do it.. Any help would be greatly appreciated! Thanks

**Comment by ToJans** [comment]
TBH I think I can't help you if can't figure it out from the demo and article; at least some experience in programming is required. Sorry about this!

**Comment by cjmeaney** [comment]
I figured it out and then I figured out a way to do it better. Glad you're
an ass.

**Comment by ToJans** [comment]
I'll just leave this here... ![shht](http://media.giphy.com/media/HTd4t5YhpGxsk/giphy.gif)
